[tool.black]
line-length = 79
skip-string-normalization = true
target-version = ['py37']
force-exclude = '/(doc/|examples/.*(schema|operations)[.]py)'

[build-system]
requires = ['setuptools', 'wheel']
build-backend = 'setuptools.build_meta:__legacy__'
