name: Python CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: dev-requirements.txt
    - name: Install dependencies
      run: |
        python -m pip --quiet --no-input install --upgrade pip wheel
        pip install -r dev-requirements.txt
    - name: Lint with flake8
      run: |
        flake8 . --config setup.cfg
    - name: Test with nose
      run: |
        ./setup.py nosetests
    - name: Build
      run: |
        ./setup.py egg_info -Db '' sdist bdist_egg
    - name: Install
      run: |
        ./setup.py install --skip-build
    - name: Test GitHub example
      run: |
        cd examples/github
        NO_DOWNLOAD=1 ./update-schema.sh
        ./update-operations.sh
    - name: Test Shopify example
      run: |
        cd examples/shopify
        NO_DOWNLOAD=1 ./update-schema.sh
        ./update-operations.sh
    - name: Coveralls
      run: coveralls --service=github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
